# Source: supabase/templates/storage/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-storage
  namespace: default
  labels:
    helm.sh/chart: supabase-0.7.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-storage
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-storage
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-storage
      automountServiceAccountToken: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        null
      initContainers:
        - name: init-db
          image: "postgres:17-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "supabase-supabase-db"
            - name: DB_PORT
              value: "5432"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h $(DB_HOST) -p $(DB_PORT) -U postgres; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
        - name: init-bucket
          image: "cgr.dev/chainguard/minio-client:latest-dev"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-minio
                  key: user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-minio
                  key: password
            
            - name: REQUEST_ALLOW_X_FORWARDED_PATH
              value: "true"
            - name: FILE_SIZE_LIMIT
              value: "52428800"
            - name: FILE_STORAGE_BACKEND_PATH
              value: "/var/lib/storage"
            - name: TENANT_ID
              value: "stub"
            - name: REGION
              value: "stub"
            - name: GLOBAL_S3_BUCKET
              value: "stub"
            - name: ENABLE_IMAGE_TRANSFORMATION
              value: "true"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until /usr/bin/mc alias set supa-minio http://supabase-supabase-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                echo "Waiting for minio to start..."
                sleep 2
              done
              /usr/bin/mc mb --ignore-existing supa-minio/$GLOBAL_S3_BUCKET
      containers:
        - name: supabase-storage
          image: "supabase/storage-api:v1.60.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: STORAGE_BACKEND
              value: "s3"
            - name: DB_DRIVER
              value: "postgres"
            - name: DB_USER
              value: "supabase_storage_admin"
            - name: DB_SSL
              value: "disable"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: supabase-minio
                  key: user

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-minio
                  key: password
            - name: DB_HOST
              value: "supabase-supabase-db"
            - name: DB_PORT
              value: "5432"
            - name: POSTGREST_URL
              value: http://supabase-supabase-rest:3000
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db
                  key: password
            - name: DB_PASSWORD_ENC
              valueFrom:
                secretKeyRef:
                  name: supabase-db
                  key: password_encoded
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: supabase-db
                  key: database
            - name: DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD_ENC)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: secret
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: secret
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: anonKey
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: serviceKey
            - name: S3_PROTOCOL_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: supabase-s3
                  key: keyId
            - name: S3_PROTOCOL_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-s3
                  key: accessKey
            - name: IMGPROXY_URL
              value: http://supabase-supabase-imgproxy:5001
            - name: GLOBAL_S3_ENDPOINT
              value: http://supabase-supabase-minio:9000
            - name: GLOBAL_S3_PROTOCOl
              value: http
            - name: GLOBAL_S3_FORCE_PATH_STYLE
              value: "true"
            
            - name: REQUEST_ALLOW_X_FORWARDED_PATH
              value: "true"
            - name: FILE_SIZE_LIMIT
              value: "52428800"
            - name: FILE_STORAGE_BACKEND_PATH
              value: "/var/lib/storage"
            - name: TENANT_ID
              value: "stub"
            - name: REGION
              value: "stub"
            - name: GLOBAL_S3_BUCKET
              value: "stub"
            - name: ENABLE_IMAGE_TRANSFORMATION
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/storage
              name: storage-data
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: supabase-storage

